### ISSUE TITLE
Feature: Reranking source documents.

### ISSUE THREAD

**Issue by KevKibe** [KevKibe/docindex#21]
- Currently the source documents are retrieved and ranked using the `vectorstore.as_retriever` default similarity score.
- This is not enough for complex queries or with a large amount of source documents.
- One solution I found out in my research is using cohere's reranking [model](https://cohere.com/blog/rerank-3)
- See :
    -  [example 1](https://medium.com/@ashpaklmulani/improve-retrieval-augmented-generation-rag-with-re-ranking-31799c670f8e) 
    - [example 2](https://gist.github.com/nreimers/0e00920aed9fcfb1581bc4f93b62363a)
    - [example 3](https://www.pinecone.io/learn/series/rag/rerankers/) 
- A concern on this is that it is a priced model and user's will need to pay to use in production.
- We can however have it as an option but not the only option.
- What do you think? @koleshjr

**Comment by koleshjr** [comment]
Yeah sounds good. Btw here is a github repo with a lot of re-rankers to choose from in a unified api
https://github.com/AnswerDotAI/rerankers
I was thinking to use it for the rerankers feature. Take a look and lemme know how you find it

**Comment by KevKibe** [comment]
Thats a much better implementation.
I'll implement it, submit a PR and tag you to review it.

**Comment by koleshjr** [comment]
Coool
